-- CreateTable
CREATE TABLE `User` (
    `id` VARCHAR(191) NOT NULL,
    `discordId` VARCHAR(191) NOT NULL,
    `username` VARCHAR(191) NOT NULL,
    `discriminator` VARCHAR(191) NULL,
    `avatar` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `User_discordId_key`(`discordId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Character` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `characterName` VARCHAR(191) NOT NULL DEFAULT '',
    `playerName` VARCHAR(191) NOT NULL DEFAULT '',
    `race` VARCHAR(191) NOT NULL DEFAULT '',
    `classAndLevel` VARCHAR(191) NOT NULL DEFAULT '',
    `background` VARCHAR(191) NOT NULL DEFAULT '',
    `alignment` VARCHAR(191) NOT NULL DEFAULT '',
    `experience` VARCHAR(191) NOT NULL DEFAULT '0',
    `strength` VARCHAR(191) NOT NULL DEFAULT '10',
    `dexterity` VARCHAR(191) NOT NULL DEFAULT '10',
    `constitution` VARCHAR(191) NOT NULL DEFAULT '10',
    `intelligence` VARCHAR(191) NOT NULL DEFAULT '10',
    `wisdom` VARCHAR(191) NOT NULL DEFAULT '10',
    `charisma` VARCHAR(191) NOT NULL DEFAULT '10',
    `armorClass` VARCHAR(191) NOT NULL DEFAULT '10',
    `initiative` VARCHAR(191) NOT NULL DEFAULT '0',
    `speed` VARCHAR(191) NOT NULL DEFAULT '30',
    `hitPointMaximum` VARCHAR(191) NOT NULL DEFAULT '',
    `currentHitPoints` VARCHAR(191) NOT NULL DEFAULT '',
    `temporaryHitPoints` VARCHAR(191) NOT NULL DEFAULT '0',
    `hitDice` VARCHAR(191) NOT NULL DEFAULT '',
    `deathSaveSuccess` VARCHAR(191) NOT NULL DEFAULT '0',
    `deathSaveFailures` VARCHAR(191) NOT NULL DEFAULT '0',
    `proficiencyBonus` VARCHAR(191) NOT NULL DEFAULT '+2',
    `acrobatics` VARCHAR(191) NOT NULL DEFAULT '0',
    `animalHandling` VARCHAR(191) NOT NULL DEFAULT '0',
    `arcana` VARCHAR(191) NOT NULL DEFAULT '0',
    `athletics` VARCHAR(191) NOT NULL DEFAULT '0',
    `deception` VARCHAR(191) NOT NULL DEFAULT '0',
    `history` VARCHAR(191) NOT NULL DEFAULT '0',
    `insight` VARCHAR(191) NOT NULL DEFAULT '0',
    `intimidation` VARCHAR(191) NOT NULL DEFAULT '0',
    `investigation` VARCHAR(191) NOT NULL DEFAULT '0',
    `medicine` VARCHAR(191) NOT NULL DEFAULT '0',
    `nature` VARCHAR(191) NOT NULL DEFAULT '0',
    `perception` VARCHAR(191) NOT NULL DEFAULT '0',
    `performance` VARCHAR(191) NOT NULL DEFAULT '0',
    `persuasion` VARCHAR(191) NOT NULL DEFAULT '0',
    `religion` VARCHAR(191) NOT NULL DEFAULT '0',
    `sleightOfHand` VARCHAR(191) NOT NULL DEFAULT '0',
    `stealth` VARCHAR(191) NOT NULL DEFAULT '0',
    `survival` VARCHAR(191) NOT NULL DEFAULT '0',
    `inspiration` VARCHAR(191) NOT NULL DEFAULT '0',
    `passiveWisdom` VARCHAR(191) NOT NULL DEFAULT '10',
    `otherProficiencies` TEXT NOT NULL DEFAULT '',
    `languages` TEXT NOT NULL DEFAULT '',
    `equipment` TEXT NOT NULL DEFAULT '',
    `attacksAndSpellcasting` TEXT NOT NULL DEFAULT '',
    `featuresAndTraits` TEXT NOT NULL DEFAULT '',
    `personalityTraits` TEXT NOT NULL DEFAULT '',
    `ideals` TEXT NOT NULL DEFAULT '',
    `bonds` TEXT NOT NULL DEFAULT '',
    `flaws` TEXT NOT NULL DEFAULT '',
    `backstory` TEXT NOT NULL DEFAULT '',
    `appearance` TEXT NOT NULL DEFAULT '',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Character_userId_key`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Character` ADD CONSTRAINT `Character_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
