-- AlterTable
ALTER TABLE `Character` ADD COLUMN `plat` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `gold` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `silver` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `copper` VARCHAR(191) NOT NULL DEFAULT '';
